src/InputUtils.ts
See: [VKUI#962](https://github.com/VKCOM/VKUI/pull/962)
=> Fix mouse detection on Android devices

build/tasks/generate_scheme.js
Иначе верхнеуровневый scheme="space_gray" перебьет scheme="bright_light"
P.S. Да, я проверил, что фоллбэки в VKUI корректно генерируются. Кстати, если `:root` поставить в конец, а не в начало, то фоллбэки оторвет.
=> added body[scheme="bright_light"] and [scheme="bright_light"] to default scheme selector

.gitignore, src/__tests__/functions.test.js, src/functions.ts
fix: preserve call orders for throttled calls
=> feat: add cancel for throttle/debounce

src/__tests__/htmlEntities.test.js, src/htmlEntities.ts, src/index.ts
Написал новую функцию, которая принимает на вход любой тип и рекурсивно перебирает объекты с массивами применяя на всех строчках decodeHTMLEntities
=> decodeHTMLEntitiesDeep: init

.eslintignore, .github/workflows/publish.yml, .gitignore, package.json, tsconfig.json, yarn.lock
=> docs: add typedoc

src/IOSDetections.ts, src/detections.ts, src/html/escape.ts
Добавляем `/*#__PURE__*/` для тришейкинга
=> fix: add __PURE__ for tree shaking

src/__tests__/react_utils.test.ts, src/react_utils.ts
Хотим в VKU использовать `hasReactNode()` из `vkjs`.
- Фикс под issue https://github.com/VKCOM/VKUI/issues/1649
- Добавил файл `react_utils.test.ts`
=> fix(hasReactNode): check value isn't empty string

babel.config.js, babel.es6.config.js, jest.config.js, package.json, package.swcrc, src/__tests__/common.test.ts, src/__tests__/duration.test.ts, src/__tests__/querystring.test.ts, src/html/__tests__/htmlEntities.test.ts, yarn.lock
Используем swc для сборки, вместо babel
=> feat: use swc

package.json, yarn.lock
=> test: rm ts-jest

package.json, yarn.lock
=> build: update @swc/core to 1.3.49

.github/workflows/inactive_contributions.yml
Добавляем ci для закрытия неактивных ишью и PR-ов
=> ci: close inactive issues and PRs

.github/dependabot.yml
- [Configuration options for the dependabot.yml file • groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
=> dependabot: use 'groups'; set schedule to weekly

.github/workflows/branch-test-coverage.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, .github/workflows/reusable_workflow_test.yml, jest.config.js, package.json
=> test: add coverage

.github/workflows/publish.yml, .github/workflows/pull_request.yml, .github/workflows/reusable_workflow_test.yml
Обновляем версию node js до 20
=> ci: update node-version to 20

package.json, yarn.lock
Заменяем @size-limit/preset-big-lib на @size-limit/file и @size-limit/webpack
- see also GHSA-78xj-cgh5-2h22
=> chore: rm @size-limit/preset-big-lib

src/IOSDetections.test.ts, src/IOSDetections.ts
- fix #426
---
Заодно поправил регулярки, т.к. **User Agent** может придти без трансформации в нижний регистр.
=> fix(checkIPadOS): check to ontouchend is exist

src/index.ts, src/type_checkers.test.ts, src/type_checkers.ts
=> feat: add isPromiseLike

src/arrays.ts
I optimized the function to reduce the number of loops and intermediate collections.
=> Optimize shuffleArray array

.github/workflows/reusable_workflow_test.yml
=> ci: Update codecov

src/typecheck/type_checkers.ts
Добавляем больше информации для функции `isNumber`
=> docs: isNumber more info

yarn.lock
=> chore(deps-dev): update yarn.lock

src/array/arrays.ts, src/internal/uniqueArray.ts
Расширяем аргументы разрешая прокидывать readonly массивы
=> feat(array): add readonly

src/async/index.ts, src/async/throttle.ts
=> feat: add ThrottledFunction
